version: "3"
services:
  app:
    container_name: Hukumka-app
    build:
      context: ./app
      dockerfile: Dockerfile_app
    ports:
      - "127.0.0.1:${APP_PORT}:5000"
    deploy:
      resources:
        limits:
          memory: 230M
  tester:
    container_name: Hukumka-tester
    env_file:
      - .env_example
    build:
      context: ./tester
      dockerfile: Dockerfile_tester
    ports:
      - "127.0.0.1:2222:22"
    depends_on:
      - app