FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    openssh-server=1:8.9p1-3ubuntu0.7 \
    pwgen=2.08-2build1 \
    git=1:2.34.1-1ubuntu1.10 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.4 \
    wget=1.21.2-2ubuntu1 \
    xvfb=2:21.1.4-2ubuntu1.7~22.04.10

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP

RUN pip install \
    yapf==0.40.2 \
    pylint==3.1.0 \
    requests==2.31.0 \
    pytest==8.1.1 \
    selenium==4.19.0 \
    webdriver-manager==4.0.1

RUN DEBIAN_FRONTEND=noninteractive TZ=Europe/Moscow apt-get install -y python3-tk=3.10.8-1~22.04

COPY tests ./tests

RUN mkdir /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    PASSWD=$(pwgen -n 8 -1 -s) && \
    echo root:"$PASSWD" | chpasswd && \
    echo "ssh password: $PASSWD"

ENTRYPOINT ["bash", "-c", "service ssh start && python3 -m http.server 3000 "]