FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    openssh-server=1:8.9p1-3ubuntu0.7 \
    pwgen=2.08-2build1 \
    git=1:2.34.1-1ubuntu1.10 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.4

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP

COPY requirements.txt ./
RUN pip3 install -r requirements.txt


COPY tests ./tests

RUN mkdir /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    PASSWD=$(pwgen -n 8 -1 -s) && \
    echo root:"$PASSWD" | chpasswd && \
    echo "ssh password: $PASSWD"

ENTRYPOINT ["bash", "-c", "service ssh start && python3 -m http.server 3000 "]