FROM ubuntu:22.04

# Installing packages
RUN apt-get update && apt-get install -y \
    git=1:2.34.1-1ubuntu1.10 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.4

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP

COPY app_patch.patch ./
RUN patch main.py app_patch.patch

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

ENTRYPOINT ["bash", "-c", "python3 main.py"]